<?xml version="1.0" encoding="UTF-8"?>
<!-- Document prolog : contains the document tags and their types -->
<!DOCTYPE music_library [
    <!ELEMENT music_library (title, artist, country, price, year)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT artist (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT year (#PCDATA)>

]>
<!--End of document prolog -->

<!-- music library document -->
<music_library>
        <title>YLO</title>
        <artist>&MS; - Jenny Dan</artist>
        <country>Germany</country>
        <price>$ 12</price>
        <year>2002</year>
</music_library>