=== Teka38/xml_and_json_adse/xsd/library.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   elementFormDefault="qualified">
	<!--
	+++++++++++++++++++++++++++++++++++++++++++++++++++++++
	Define a reusable group
	+++++++++++++++++++++++++++++++++++++++++++++++++++++++
	-->
	<xs:group name="authorgroup">
		<xs:sequence>
			<xs:element name="author" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="firstname" type="xs:string"/>
						<xs:element name="lastname" type="xs:string"/>
					</xs:sequence>
					<xs:attribute name="id" type="xs:ID" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>

	<!--
	+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	Define a book complex type: demonstrating element content
	+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	-->
	<xs:complexType name="booktype">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="publisher">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="city" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<!-- use the author group -->
			<xs:group ref="authorgroup"/>
			<xs:element name="description" minOccurs="0">
				<!-- mixed content example -->
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="2"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
<!--
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Root element (library).
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-->

<xs:element name="library">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="book" type="booktype" minOccurs="1"
                        maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

=== Teka38/xml_and_json_adse/xml/library.xml
<?xml version="1.0" encoding="utf-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/library.xsd">
    <book isbn="978-0123458-47-2">
        <title>Learning XML</title>
        <publisher>
            <name>Techbooks Press</name>
            <city>Nairobi</city>
                    </publisher>
        <author id="au0001">
            <firstname>Mary</firstname>
            <lastname>Wanjiku</lastname>
        </author>
        <author id="au0002">
            <firstname>John</firstname>
            <lastname>Mutindi</lastname>
        </author>
                <description>
            This book is a beginner-friendly guide to XML.
            <note>Update for XML 1.2</note>
            <note>Includes xml schema exercises</note>
        </description>
    </book>
        <book isbn="978-0-987548-32-1">
        <title>Advanced XSD Concepts</title>
        <publisher>
            <name>SchemaWorks</name>
            <city>Mombasa</city>
        </publisher>
        <author id="au0003">
            <firstname>Anne</firstname>
                        <lastname>Mutisya</lastname>
        </author>
    </book>
</library>
